// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRis4SGgUtRE0hODLDlIYxYCJFr_ix57o',
    appId: '1:496269700141:web:598a5672706d8aa110dca4',
    messagingSenderId: '496269700141',
    projectId: 'weshop8230',
    authDomain: 'weshop8230.firebaseapp.com',
    storageBucket: 'weshop8230.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAXGsS_jhe2XSmvCSY95n4zPUQCK6O9cg',
    appId: '1:496269700141:android:d417554654d7ffc810dca4',
    messagingSenderId: '496269700141',
    projectId: 'weshop8230',
    storageBucket: 'weshop8230.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPYkThp6qCKpjMrGrixTFqkYYRbzhHFTY',
    appId: '1:496269700141:ios:285191840bc36b6e10dca4',
    messagingSenderId: '496269700141',
    projectId: 'weshop8230',
    storageBucket: 'weshop8230.appspot.com',
    androidClientId: '496269700141-g2eas241cj6cvvbu94ooju20qub1g7u3.apps.googleusercontent.com',
    iosClientId: '496269700141-aadndh4eadfm74acg8mddbvbau9b3f8b.apps.googleusercontent.com',
    iosBundleId: 'com.int2.ecommerceInt2',
  );
}
